site_name: SkillAPI 文档
site_url: https://junzzzz.github.io/SkillAPI-docs/
site_author: Junzzzz
site_description: "Minecraft 1.7.10 动态技能编辑模组"
edit_uri: https://github.com/Junzzzz/SkillAPI-docs/blob/main/docs/

# Repository
# repo_name: Junzzzz/SkillAPI
# repo_url: https://github.com/Junzzzz/SkillAPI

# Copyright
copyright: Copyright &copy; 2022 Junzzzz

# Configuration
theme:
  name: material
  language: zh
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换夜晚模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换白天模式
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      # auto_title: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Junzzzz
      repo: SkillAPI
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - '首页':
    - '概述': index.md
    - '介绍': introduction.md
  - '使用方法':
    - '技能':      
      - '静态技能': usage/skill/static-skill.md
      - '技能效果': usage/skill/skill-effect.md
      - '额外参数传递': usage/skill/skill-extra-info.md
    - '增强':      
        - '数据包': usage/enhanced/packet.md
        - '监听事件': usage/enhanced/event.md
    - '工具类': 
        - '消息': usage/utils/message.md
        - '翻译': usage/utils/translation.md
  - '高级':
    - '注解处理器': advanced/annotation-processor.md      

